using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
// <copyright file="PropertiesTest.GetFileProperties.g.cs">Copyright ©  2014</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace PhotoOrganizaer.FileManagement
{
    public partial class PropertiesTest
    {
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetFilePropertiesThrowsArgumentNullException56()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[ExpectedException(typeof(ArgumentException))]
public void GetFilePropertiesThrowsArgumentException417()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties("\0");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[PexRaisedException(typeof(ArgumentException))]
public void GetFilePropertiesThrowsArgumentException679()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties(" ");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetFileProperties868()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties("0");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetFileProperties909()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties(".");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetFileProperties652()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties("~");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[PexRaisedException(typeof(ArgumentException))]
public void GetFilePropertiesThrowsArgumentException378()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties("  ");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetFileProperties563()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties("0\u00a0");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetFileProperties398()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties("00");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetFileProperties382()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties(".0");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetFileProperties757()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties("..");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetFileProperties380()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties("~0");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetFileProperties416()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties("~~");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetFileProperties89()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties("0\u00a0\u00a0 ");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetFileProperties758()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties("0  0");
}
[TestMethod]
[PexGeneratedBy(typeof(PropertiesTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetFileProperties890()
{
    Dictionary<string, string> dictionary;
    dictionary = this.GetFileProperties("\u1000\u0080\u4000\u4000 \u0101     (");
}
    }
}
